# Generated by Django 4.1.6 on 2023-10-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happ', '0003_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doc_image',
            field=models.ImageField(upload_to='Doctors'),
        ),
    ]
