# Generated by Django 4.1.6 on 2023-10-30 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happ', '0005_remove_doctors_doc_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctorsnew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=255)),
                ('doc_spec', models.CharField(max_length=200)),
                ('doc_image', models.ImageField(upload_to='Doctorsnew')),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happ.departments')),
            ],
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
